compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
    fsdp_auto_wrap_policy: TRANSFORMER_LAYER_WRAP
    fsdp_backward_prefetch: BACKWARD_PREFETCH_DDP
    fsdp_offload_params: false
    fsdp_sharding_strategy: 1
    fsdp_state_dict_type: FULL_STATE_DICT
    fsdp_transformer_layer_cls_to_wrap: Wav2Vec2EncoderLayer
    fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: 'fp16'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
