compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
use_cpu: false
rdzv_backend: static
same_network: true
